services:
  api:
    build: ./aerolive-backend
    container_name: airport_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ML_SERVICE_URL: http://ai:8000
      PORT: "3000"
    restart: unless-stopped
    networks:
      - aerolive_net

  ai:
    build: ./aerolive-ai
    container_name: airport_ai
    restart: unless-stopped
    networks:
      - aerolive_net

  frontend:
    build: ./aerolive-frontend
    container_name: airport_frontend
    ports:
      - "3080:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - aerolive_net

networks:
  aerolive_net:
    driver: bridge
