server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        resolver 127.0.0.11 valid=10s;
        set $api_upstream http://api:3000;
<<<<<<< HEAD
        proxy_pass $api_upstream;
=======
        proxy_pass $api_upstream;
>>>>>>> b83138e530ac7668cf239c44706b1cc0a57cb1e2
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
